# Generated by Django 2.2.1 on 2019-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('train_no', models.CharField(max_length=5)),
                ('ticket_no', models.CharField(max_length=8)),
                ('doj', models.DateField()),
                ('boarding_station', models.CharField(max_length=40)),
                ('destination_station', models.CharField(max_length=40)),
                ('complaint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('mobileNo', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('from_station', models.CharField(max_length=40)),
                ('to_station', models.CharField(max_length=40)),
                ('doj', models.DateField()),
                ('ticket_no', models.CharField(max_length=8, unique=True)),
                ('train_no', models.CharField(max_length=5)),
                ('train_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.CharField(max_length=50, unique=True)),
                ('trainNumber', models.CharField(max_length=5, unique=True)),
                ('fromStation', models.CharField(max_length=40)),
                ('toStation', models.CharField(max_length=40)),
                ('stoppages', models.FileField(upload_to='uploads/train_stoppages/')),
                ('runningDays', models.CharField(max_length=16)),
                ('capacity', models.IntegerField()),
                ('booked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
    ]
