name: DeployToHerokuServer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spandan-project"
          heroku_email: "2spandan2@gmail.com"

    - name: Successful Message
      run: echo Successfully Deployed!!

